# Generated by Django 3.2.5 on 2021-08-31 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dog',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelTable(
            name='dog',
            table='tbl_dog',
        ),
    ]
